# This workflow runs every Saturday @ 1900 UTC (NOON PST)
name: i18n download bot
on:
  push:
    branches-ignore:
      - '**'
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destinyitemmanager.com
        uses: actions/checkout@v3

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Download updated i18n files
        uses: crowdin/github-action@1.4.1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
          source: template/locales/en.json
          translation: template/locales/%android_code%.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate localized webpages
        run: yarn install && yarn i18n

      - uses: dorny/paths-filter@v2 ## porcelain check
        id: filter
        with:
          base: HEAD
          filters: |
            changed:
              - '**'

      - name: Commit files
        if: steps.filter.outputs.changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: i18n
          commit_user_name: DIM i18n Bot
          commit_user_email: destinyitemmanager@gmail.com
          commit_author: DIM i18n Bot <destinyitemmanager@gmail.com>