# This workflow runs whenever dim.json is updated on the master branch
# It updates crowdin with new translation strings
# and notifies the #i18n @i18n in Discord of the new translations.
name: i18n upload bot
on:
  workflow_dispatch:
  push:
    paths:
      - "template/locales/en.json"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destinyitemmanager.com
        uses: actions/checkout@v3

      - name: Sort website json
        run: yarn install && yarn i18n:json

      - name: Upload updated website json to crowdin
        uses: crowdin/github-action@1.4.1
        with:
          upload_sources: true
          upload_translations: false
          source: template/locales/en.json
          translation: template/locales/%android_code%.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: i18n-diff
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            i18n:
              - 'src/locale/en.json'

      - name: Discord notification
        # Possibly add back in the number of changes via `git diff --numstat -- src/locale/en.json` and some awk or grep magic
        if: ${{ steps.filter.outputs.i18n == 'true' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"DIM Website- crowdin", "color": F37422, "url": "https://crowdin.com/project/destiny-item-manager-website","description": "Translation(s) for the website have been added or changed on crowdin."  }]'
        uses: Ilshidur/action-discord@master
        with:
          args: "<@&622449489008918548>"

