# This workflow runs whenever dim.json is updated on the master branch
# It updates crowdin with new translation strings
# and notifies the #i18n @i18n in Discord of the new translations.
name: i18n upload bot
on:
  workflow_dispatch:
  push:
    paths:
      - "template/locales/en.json"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destinyitemmanager.com
        uses: actions/checkout@v2

      - name: Sort website json
        run: yarn install && yarn i18n:json

      - name: Upload updated website json to crowdin
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: true
          upload_translations: false
          source: template/locales/en.json
          translation: template/locales/%android_code%.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          #DISCORD_EMBEDS: ${{ toJSON(secrets.DISCORD_EMBEDS) }}
        uses: Ilshidur/action-discord@master
        with:
          args: "<@&622449489008918548> - New translations for the website have been added to crowdin. https://crowdin.com/project/destiny-item-manager-website"
