# This workflow runs every Saturday @ 1900 UTC (NOON PST)
name: i18n download bot
on:
  push:
    branches-ignore:
      - '**'
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destinyitemmanager.com
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Download updated i18n files
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
          source: template/locales/en.json
          translation: template/locales/%android_code%.json
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sort website json
        run: |
          allLocales=("en" "de" "es" "es-mx" "fr" "it" "ja" "ko" "pl" "pt-br" "ru" "zh-chs" "zh-cht")
          for lang in ${allLocales[@]}; do
            jq -S . template/locales/"$lang".json > template/locales/"$lang"_sorted.json && mv template/locales/"$lang"_sorted.json template/locales/"$lang".json
          done

      - name: Generate localized webpages
        run: yarn install && yarn i18n

      - name: Check for new files
        id: porcelain
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Create Pull Request
        if: steps.porcelain.outputs.porcelain
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: i18n
          committer: DIM i18n Bot <destinyitemmanager@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[i18n] Updates'
          body: i18n updates
          labels: i18n, automated pr
          reviewers: delphiactual
          branch: i18n
